Fixed matched and missing
analysis-dev/save-cloud pull request #503
Opened 2021-12-17 18:18 UTC by Cheshiriks

What's done:
* fixed matched and missing

2021-12-18 08:35 UTC, petertrr requested changes

2021-12-18 08:35 UTC, petertrr commented on save-backend/src/main/kotlin/org/cqfn/save/backend/service/TestExecutionService.kt
> +                    it.matchedWarnings = testExecDto.matchedWarnings
Please add assert on missed/matched count in `TestExecutionControllerTest`, so that we don't run in this issue again

2021-12-18 20:36 UTC, akuleshov7 approved these changes

2021-12-18 20:36 UTC, akuleshov7 commented
I tested it, works fine

2022-01-10 09:44 UTC, petertrr approved these changes

2022-01-10 10:48 UTC, akuleshov7 approved these changes

2022-01-10 11:01 UTC, merged